title: Digital C-Fiber Research Group
description: Computational models of human C-fibers for neuropathic pain research
baseurl: ""
url: "https://digital-c-fiber.github.io"
theme: minima
markdown: kramdown
